parameters:
- name: environment
  default: ''
- name: appName
  default: ''

jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-16.04'
    environment: ${{ parameters.environment }}
    variables:
    - group: 'Release'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: 'Resource Manager - Tailspin - Space Game'
              appName: '${{ parameters.appName }}'
              appType: webAppLinux
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'